# Generated by debtap
# Maintainer: Vincent
# Contributor: Vincent
pkgname=splashtop-streamer
pkgver=3.0.2.0
pkgrel=1
pkgdesc="Splashtop Remote Streamer. Remotely access your desktop from any device from anywhere!"
arch=('x86_64')
url=""
license=('')
groups=('')
provides=('splashtop-streamer')
depends=('gcc>=5' 'bash-completion>=2.11' 'curl>=7.47.0' 'dbus>=1.9.14' 'desktop-file-utils' 'gcc>=3.0' 'gcc-libs' 'gdk-pixbuf2>=2.25.2' 'glib2>=2.39.4' 'glibc>=2.15' 'gtk3>=3.5.12' 'hicolor-icon-theme' 'libappindicator-gtk3>=0.2.92' 'libnotify>=0.7.0' 'libpulse>=0.99.1' 'libxcb>=1.3' 'lshw' 'mumble' 'pam>=0.99.7.1' 'systemd-libs>=217' 'util-linux' 'util-linux-libs>=2.16' 'xcb-util>=0.4.0' 'xcb-util-keysyms>=0.4.0' 'xorg-appres>=1' 'zlib>=1.2.0')
backup=('etc/dbus-1/system.d/com.splashtop.streamer.conf')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source_x86_64=("source.tar.gz::https://download.splashtop.com/linux/STB_CSRS_Ubuntu_v${pkgver}_amd64.tar.gz")
sha512sums_x86_64=('8ab489501ce63c6ddfa7c2bbe2db46244e604a256671c5e3b75634dcb9c3e838dc67039567f00163489b4df338bd795d98a51dcea9bce14d9263e2ce53ead72b')

package(){
	ar x "${srcdir}/Splashtop_Streamer_Ubuntu_amd64.deb"

	# Extract package data
	tar xf data.tar.xz -C "${pkgdir}"

	install -D -m644 "${pkgdir}/opt/splashtop-streamer/EULA.htm" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

}
